import {
  AlertTriangle,
  ArrowRight,
  BookMarked,
  Check,
  Command,
  CreditCard,
  HelpCircle,
  Import,
  Laptop,
  LayoutDashboardIcon,
  Loader2,
  LockIcon,
  LogIn,
  MonitorSpeaker,
  Moon,
  MoreVertical,
  Pizza,
  Plus,
  Settings,
  SunMedium,
  Target,
  Trash,
  User,
  User2Icon,
  X
} from 'lucide-react';
import { ChatBubbleIcon } from '@radix-ui/react-icons';

export const Icons = {
  dashboard: LayoutDashboardIcon,
  logo: Command,
  login: LogIn,
  close: X,
  monitor: MonitorSpeaker,
  import: Import,
  profile: User2Icon,
  spinner: Loader2,
  trash: Trash,
  settings: Settings,
  billing: CreditCard,
  ellipsis: MoreVertical,
  add: Plus,
  warning: AlertTriangle,
  user: User,
  arrowRight: ArrowRight,
  help: HelpCircle,
  pizza: Pizza,
  sun: SunMedium,
  moon: Moon,
  laptop: Laptop,
  target: Target,
  comment: ChatBubbleIcon,
  check: Check,
  category: BookMarked,
  lock: LockIcon
};
